name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install ShellCheck
        run: sudo apt-get install -y shellcheck
      - name: Lint main script
        run: shellcheck install_icinga2.sh
      - name: Lint lib scripts
        run: |
          for f in lib/*.sh; do
            shellcheck "$f"
          done
